- hosts: apache
  vars:
    - pkg: apache2
    - apache_module: rewrite
    - msg: "Hello World!"
  sudo: yes
  tasks:
    - name: install apache2
      apt: name={{pkg}} update_cache=yes state=latest

    - name: enabled mod_rewrite
      apache2_module: name={{apache_module}} state=present
      notify:
        - restart apache2

    - name: apache2 listen on port 8081
      lineinfile: path=/etc/apache2/ports.conf regexp="^Listen 80" line="Listen 8081" state=present
      notify:
        - restart apache2

    - name: add index.html 
      copy:
        dest: /var/www/html/index.html
        content: "{{ msg }}"

  handlers:
    - name: restart apache2
      service: name={{pkg}} state=restarted

