- hosts: apache
  vars:
    - pkg: apache2
  sudo: yes
  tasks:
    - name: uninstall apache2
      apt: name={{pkg}}  state=absent
    - name: remove frontend files
      file:
        path: "/var/www/"
        state: absent


