---
- name: Verify local file
  local_action: stat path={{ defaultPath }}
  register: "localFileStat"

- debug: var=localFileStat verbosity=True

- name: Copy file
  copy: src={{defaultPath}} dest={{destPath}}
  register: 'FileItem'
  notify:
  - sample-handler
  with_items:
  - "{{ localFileStat}}"
  when: item.stat.exists == True

- debug: var=FileItem verbosity=True
- debug: var=show_msg verbosity=True
  
